### PR TITLE
Add PhpStorm as a role.

### PR DESCRIPTION
**Pull request by func0der**
I hope this setup is correct. 
If you have any notes, please tell me and I address them :)

### CODE REVIEW

**Comment by func0der** [comment]
Workflow runs are missing. 
Have you considered turning them on for PRs too?

**Comment by x86-39** [comment]
> Workflow runs are missing. Have you considered turning them on for PRs too?

Just tried something.. let's see if it works!

Thanks for the PR!!!

**Comment by x86-39** [comment]
Looks good!! Thank you!

**Comment by func0der** [comment]
Could you tag and release this too, please :)

**Comment by func0der** [comment]
@diademiemi  :) 
About that release in the galaxy :)

**Comment by x86-39** [comment]
Apologies for the delay! Doing that right now

**Comment by func0der** [comment]
Appreciated :) 

I know, you can never demand from open source. :) 
Thank you for putting your time into this.

**Pull request merged**
